services:
  redis_db:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puzzle-microservice
    environment:
      - REDIS_URL=redis_db
    ports:
      - '3001:3001'
    volumes:
      - ./src:/app/src
    depends_on:
      - redis_db


      


volumes:
  redis:
    driver: local