name: Puzzle Service
services:
  redis_db:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puzzle-microservice
    environment:
      - REDIS_URL=redis://redis_db:6379
    ports:
      - '3001:3002'
    depends_on:
      - redis_db